/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tampilan;

/**
 *
 * @author Asus
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        KASIR = new javax.swing.JMenuItem();
        PELANGGAN = new javax.swing.JMenuItem();
        BARANG = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        NOTA = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("MASTER");

        KASIR.setText("KASIR");
        KASIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KASIRActionPerformed(evt);
            }
        });
        jMenu1.add(KASIR);

        PELANGGAN.setText("PELANGGAN");
        PELANGGAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PELANGGANActionPerformed(evt);
            }
        });
        jMenu1.add(PELANGGAN);

        BARANG.setText("BARANG");
        BARANG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BARANGActionPerformed(evt);
            }
        });
        jMenu1.add(BARANG);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("TRANSAKSI");

        NOTA.setText("NOTA");
        NOTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NOTAActionPerformed(evt);
            }
        });
        jMenu2.add(NOTA);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 736, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KASIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KASIRActionPerformed
        // TODO add your handling code here:
        Kasir frmP = new Kasir();
        frmP.setVisible(true);
    }//GEN-LAST:event_KASIRActionPerformed

    private void PELANGGANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PELANGGANActionPerformed
        // TODO add your handling code here:
        Pelanggan frmP = new Pelanggan();
        frmP.setVisible(true);
    }//GEN-LAST:event_PELANGGANActionPerformed

    private void BARANGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BARANGActionPerformed
        // TODO add your handling code here:
        Barang frmP = new Barang();
        frmP.setVisible(true);
    }//GEN-LAST:event_BARANGActionPerformed

    private void NOTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NOTAActionPerformed
        // TODO add your handling code here:
        Nota frmP = new Nota();
        frmP.setVisible(true);
    }//GEN-LAST:event_NOTAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BARANG;
    private javax.swing.JMenuItem KASIR;
    private javax.swing.JMenuItem NOTA;
    private javax.swing.JMenuItem PELANGGAN;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
