/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tampilan;
import java.sql.*; 
import java.text.SimpleDateFormat; 
import javax.swing.JOptionPane; 
import javax.swing.table.DefaultTableModel; 
import javax.swing.JSpinner; 
import Koneksi.Koneksi; 
/**
 *
 * @author Asus
 */
public class Nota extends javax.swing.JFrame {
public String id, nama, jenis, telp, almt; 
public String kdbrg, nmbrg, jenisbrg, hb, hj; 
private Connection conn = new Koneksi().connect(); 
private DefaultTableModel tabmode; 
    /**
     * Creates new form Nota
     */
    public Nota() {
        initComponents();
        String KD = UserID.getUserLogin(); 
        jLabel16.setText(KD); 
        kosong(); 
        aktif(); 
        autonumber(); 
        nama();
    }
    
    protected void nama(){ 
    try { 
        String sql = "SELECT * FROM kasir WHERE `USERNAME`='"+jLabel16.getText()+"'"; 
        Statement stat = conn.createStatement(); 
        ResultSet hasil = stat.executeQuery(sql); 
        if(hasil.next()){ 
        namakasir.setText(hasil.getString("NAMA KASIR")); 
    } 
    } catch (SQLException e){ 
        JOptionPane.showMessageDialog(null, "data gagal dipanggil"+e); 
    } 
}
    
//    protected void nama() {
//    try {
//        String sql = "SELECT * FROM kasir WHERE USERNAME = ?";
//        PreparedStatement pst = conn.prepareStatement(sql);
//        pst.setString(1, jLabel16.getText());
//
//        ResultSet hasil = pst.executeQuery();
//        if (hasil.next()) {
//            namakasir.setText(hasil.getString("NAMA_KASIR"));
//        } else {
//            JOptionPane.showMessageDialog(null, "Data tidak ditemukan.");
//        }
//
//    } catch (SQLException e) {
//        JOptionPane.showMessageDialog(null, "Data gagal dipanggil: " + e.getMessage());
//    }
//}

    
    protected void aktif(){ 
        txtqty.requestFocus(); 
        jtgl.setEditor(new JSpinner.DateEditor(jtgl,"yyyy/MM/dd")); 
        Object[] Baris ={"KD Barang", "Nama", "Harga Beli", "Harga Jual", "QTY", "Total"}; 
        tabmode = new DefaultTableModel(null, Baris); 
        tbltransaksi.setModel(tabmode); 
    }
    
    protected void kosong(){ 
        txtid.setText(""); 
        txtnm.setText(""); 
        txtalmt.setText(""); 
        txtkdbrg.setText(""); 
        txtnmbrg.setText(""); 
        txthb.setText(""); 
        txthj.setText(""); 
        txtqty.setText(""); 
        txttotal.setText(""); 
    }
    
    protected void autonumber(){ 
    try { 
        String sql = "SELECT idnota FROM nota order by idnota asc"; 
        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery(sql); 
        txtidnota.setText("IN0001"); 
        while (rs.next()) { 
        String id_nota = rs.getString("idnota").substring(2); 
        int AN = Integer.parseInt(id_nota) + 1; 
        String Nol = ""; 
        if(AN<10) 
        {Nol = "000";} 
        else if (AN<1000) 
        {Nol = "00";} 
        else if(AN<100) 
        {Nol = "0";} 
        else if (AN<10000) 
        {Nol = "";} 
        txtidnota.setText("IN" + Nol + AN); 
        } 
    }catch(Exception e){ 
        JOptionPane.showMessageDialog(null, "Auto Number Gagal" +e); 
    } 
    }
    
    public void itemTerpilih(){ 
        popuppelanggan Pp = new popuppelanggan(); 
        Pp.plgn= this; 
        txtid.setText(id); 
        txtnm.setText(nama); 
        txtalmt.setText(almt); 
    }
    
    public void itemTerpilihBrg() {
        popupbarang Pbrg = new popupbarang();
        Pbrg.brg = this;
        txtkdbrg.setText(kdbrg);
        txtnmbrg.setText(nmbrg);
        txthb.setText(hb);
        txthj.setText(hj);
        txtqty.requestFocus();
}

    
    public void hitung(){ 
        int total = 0; 
        for (int i=0; i< tbltransaksi.getRowCount(); i++){ 
        int amount = Integer.valueOf(tbltransaksi.getValueAt(i, 5).toString()); 
        total += amount; 
        } 
        txtttotal.setText(Integer.toString(total)); 
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtidnota = new javax.swing.JTextField();
        txtnm = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtalmt = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtnmbrg = new javax.swing.JTextField();
        txtkdbrg = new javax.swing.JTextField();
        namakasir = new javax.swing.JLabel();
        jtgl = new javax.swing.JSpinner();
        bcarip = new javax.swing.JButton();
        txthb = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel166 = new javax.swing.JLabel();
        txthj = new javax.swing.JTextField();
        txtqty = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();
        jLabel200 = new javax.swing.JLabel();
        btambah = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbltransaksi = new javax.swing.JTable();
        bsimpan = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        bbatal = new javax.swing.JButton();
        bkeluar = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        txtttotal = new javax.swing.JTextField();
        bcaribrg1 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel2.setText("NOTA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 35, -1, -1));

        jLabel3.setText("ID KASIR");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 103, -1, -1));

        jLabel4.setText("ID NOTA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 141, -1, -1));

        jLabel5.setText("NAMA");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 205, -1, -1));

        jLabel6.setText("ID PELANGGAN");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 170, -1, -1));

        jLabel7.setText("ALAMAT");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 253, -1, -1));

        txtidnota.setPreferredSize(new java.awt.Dimension(250, 26));
        txtidnota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidnotaActionPerformed(evt);
            }
        });
        getContentPane().add(txtidnota, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 141, 140, -1));

        txtnm.setPreferredSize(new java.awt.Dimension(250, 26));
        getContentPane().add(txtnm, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 211, 140, -1));

        txtid.setPreferredSize(new java.awt.Dimension(250, 26));
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 176, 140, -1));

        jLabel16.setText("ID KASIR");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 103, -1, -1));

        txtalmt.setColumns(20);
        txtalmt.setRows(5);
        jScrollPane1.setViewportView(txtalmt);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 253, 140, -1));

        jLabel9.setText("NAMA KASIR");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 103, -1, -1));

        jLabel10.setText("TANGGAL");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 126, -1, -1));

        jLabel11.setText("NAMA BARANG");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 193, -1, -1));

        jLabel12.setText("KD BARANG");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 158, -1, -1));

        jLabel13.setText("HARGA BELI");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 237, -1, -1));

        txtnmbrg.setPreferredSize(new java.awt.Dimension(250, 26));
        getContentPane().add(txtnmbrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 195, 140, -1));

        txtkdbrg.setPreferredSize(new java.awt.Dimension(250, 26));
        getContentPane().add(txtkdbrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 158, 140, -1));

        namakasir.setText("Nama kasir");
        getContentPane().add(namakasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 103, -1, -1));

        jtgl.setModel(new javax.swing.SpinnerDateModel());
        jtgl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jtgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 123, 140, -1));

        bcarip.setText("CARI");
        bcarip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcaripActionPerformed(evt);
            }
        });
        getContentPane().add(bcarip, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, -1, -1));

        txthb.setPreferredSize(new java.awt.Dimension(250, 26));
        getContentPane().add(txthb, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 230, 140, -1));

        jLabel15.setText("QTY");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 310, -1, -1));

        jLabel166.setText("HARGA JUAL");
        getContentPane().add(jLabel166, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 266, -1, -1));

        txthj.setPreferredSize(new java.awt.Dimension(250, 26));
        getContentPane().add(txthj, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 266, 140, -1));

        txtqty.setPreferredSize(new java.awt.Dimension(250, 26));
        txtqty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqtyActionPerformed(evt);
            }
        });
        getContentPane().add(txtqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 301, 140, -1));

        txttotal.setPreferredSize(new java.awt.Dimension(250, 26));
        getContentPane().add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 358, 140, -1));

        jLabel200.setText("TOTAL");
        getContentPane().add(jLabel200, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 361, -1, -1));

        btambah.setText("TAMBAH");
        btambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btambahActionPerformed(evt);
            }
        });
        getContentPane().add(btambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, 271, -1));

        tbltransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbltransaksi);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 646, 114));

        bsimpan.setText("SIMPAN");
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });
        getContentPane().add(bsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 610, -1, -1));

        bhapus.setText("HAPUS");
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });
        getContentPane().add(bhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 560, -1, -1));

        bbatal.setText("BATAL");
        bbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbatalActionPerformed(evt);
            }
        });
        getContentPane().add(bbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 610, -1, -1));

        bkeluar.setText("KELUAR");
        bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(bkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 610, -1, -1));

        jLabel18.setText("TOTAL HARGA");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 610, -1, -1));

        txtttotal.setPreferredSize(new java.awt.Dimension(250, 26));
        txtttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtttotalActionPerformed(evt);
            }
        });
        getContentPane().add(txtttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 610, 140, -1));

        bcaribrg1.setText("CARI");
        bcaribrg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcaribrg1ActionPerformed(evt);
            }
        });
        getContentPane().add(bcaribrg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 160, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidnotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidnotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidnotaActionPerformed

    private void bcaripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcaripActionPerformed
        // TODO add your handling code here:
        popuppelanggan Pp = new popuppelanggan();
        Pp.plgn = this;
        Pp.setVisible(true);
        Pp.setResizable(false);
    }//GEN-LAST:event_bcaripActionPerformed

    private void txtqtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtqtyActionPerformed
        // TODO add your handling code here:
        int xhrgj = Integer.parseInt(txthj.getText()); 
        int xqty = Integer.parseInt(txtqty.getText()); 
        int xjml = xhrgj*xqty; 
        txttotal.setText(String.valueOf(xjml)); 
    }//GEN-LAST:event_txtqtyActionPerformed

    private void btambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btambahActionPerformed
        // TODO add your handling code here:
        try{ 
            String kode = txtkdbrg.getText(); 
            String nama = txtnmbrg.getText(); 
            int hargab = Integer.parseInt(txthb.getText()); 
            int hargaj = Integer.parseInt(txthj.getText()); 
            int qty = Integer.parseInt(txtqty.getText()); 
            int total = Integer.parseInt(txttotal.getText()); 
            tabmode.addRow(new Object[]{kode, nama, hargab, hargaj, qty, total}); 
            tbltransaksi.setModel(tabmode); 
        } 
            catch(Exception e) 
        { 
            System.out.println("Error: "+e); 
        } 
            txtkdbrg.setText(""); 
            txtnmbrg.setText(""); 
            txthb.setText(""); 
            txthj.setText(""); 
            txtqty.setText(""); 
            txttotal.setText(""); 
            hitung(); 
    }//GEN-LAST:event_btambahActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        // TODO add your handling code here:
        int index = tbltransaksi.getSelectedRow(); 
        tabmode.removeRow(index); 
        tbltransaksi.setModel(tabmode); 
        hitung(); 
    }//GEN-LAST:event_bhapusActionPerformed

    private void txtttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtttotalActionPerformed

    private void bcaribrg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcaribrg1ActionPerformed
        // TODO add your handling code here:
         popupbarang Pbrg = new popupbarang();
        Pbrg.brg = this;
        Pbrg.setVisible(true);
        Pbrg.setResizable(false);
    }//GEN-LAST:event_bcaribrg1ActionPerformed

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        // TODO add your handling code here: 
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd"); 
        String fd = sdf.format(jtgl.getValue()); 
        String sql = "insert into nota values (?,?,?,?)"; 
        String zsql = "insert into isi values (?,?,?,?,?)"; 
        try{ 
            PreparedStatement stat = conn.prepareStatement(sql); 
            stat.setString(1, txtidnota.getText()); 
            stat.setString(2, fd); 
            stat.setString(3, txtid.getText()); 
            stat.setString(4, jLabel16.getText()); 
            stat.executeUpdate(); 
            int t = tbltransaksi.getRowCount(); 
            for(int i=0; i<t; i++) 
        { 
            String xkd = tbltransaksi.getValueAt(i, 0).toString(); 
            String xhb = tbltransaksi.getValueAt(i, 2).toString(); 
            String xhj = tbltransaksi.getValueAt(i, 3).toString(); 
            String xqty = tbltransaksi.getValueAt(i, 4).toString(); 
            PreparedStatement stat2 = conn.prepareStatement(zsql); 
            stat2.setString(1, txtidnota.getText()); 
            stat2.setString(2, xkd); 
            stat2.setString(3, xhb); 
            stat2.setString(4, xhj); 
            stat2.setString(5, xqty); 
            stat2.executeUpdate(); 
        } 
            JOptionPane.showMessageDialog(null, "data berhasil disimpan"); 
        } 
            catch (SQLException e){ 
            JOptionPane.showMessageDialog(null, "data gagal disimpan"+e); 
            kosong(); 
            aktif(); 
            autonumber(); 
        } 
        
    }//GEN-LAST:event_bsimpanActionPerformed

    private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_bkeluarActionPerformed

    private void bbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbatalActionPerformed
        // TODO add your handling code here:
        aktif();
        kosong();
        autonumber();
    }//GEN-LAST:event_bbatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbatal;
    private javax.swing.JButton bcaribrg1;
    private javax.swing.JButton bcarip;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bkeluar;
    private javax.swing.JButton bsimpan;
    private javax.swing.JButton btambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel166;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel200;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JSpinner jtgl;
    private javax.swing.JLabel namakasir;
    private javax.swing.JTable tbltransaksi;
    private javax.swing.JTextArea txtalmt;
    private javax.swing.JTextField txthb;
    private javax.swing.JTextField txthj;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtidnota;
    private javax.swing.JTextField txtkdbrg;
    private javax.swing.JTextField txtnm;
    private javax.swing.JTextField txtnmbrg;
    private javax.swing.JTextField txtqty;
    private javax.swing.JTextField txttotal;
    private javax.swing.JTextField txtttotal;
    // End of variables declaration//GEN-END:variables
}
